branches:
  only:
  - develop
language: node_js
node_js:
- '0.12'
before_install:
- pwd
install:
- npm run prepare
before_script:
- pwd
script:
- npm run test_travis
after_failure: cat ./sauce_connect.log
after_success:
- node build-config/deployCrx.js
env:
  global:
  - USE_SAUCE=true
  - secure: onYFok5CBcV1116+kOEZJsyDB1kRHF+8deU1cll3vhxBEM/woSRvpso32oxjuza+or2uXuBT1SiZn0oTmuKD/TRaKw1e8wTtX6kQzCUhyeGoAyJH8SeGIwkt8+x232rFUe2bNLr6e0JAGZMtTjk1Q1zqfONNWAQzsUWDeUqvwt8=
  matrix:
  - MODE=chromeApp
  - MODE=firefox
addons:
  sauce_connect:
    username: readium
    access_key: a36ebc10-e514-4da6-924c-307aec513550
deploy:
  provider: divshot
  skip_cleanup: true
  api_key:
    secure: Y/evg7Yp4WsFjDOJBkQcrJ4/XTQbKYQjdX5iSaHu/JLo/GAJEIqxnEHavprBqHE/KvLjvCStn/bZ15oAMhq+EiJ+VNpZRWmTaZh6SA2CmtJeMtRqUwhpclvbCzSm0Z/8RFHhTmsNh7P5ICuFFWXv/pJ644trfh3Rg8abOIDqvww=
  environment: production
  on:
    repo: readium/readium-js-viewer
    branch: develop
    condition: $MODE = firefox
